// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: gqxPS4AgvrvZFiLQ3PbJ65
// Component: cLCF7A0Hcm_r

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import * as pp from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_app_starter_hostless_no_auth_test_css from "../app_starter_hostless_no_auth_test/plasmic_app_starter_hostless_no_auth_test.module.css"; // plasmic-import: waVhN6sKC41JduCkjZHFuq/projectcss
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_software_foundry.module.css"; // plasmic-import: gqxPS4AgvrvZFiLQ3PbJ65/projectcss
import sty from "./PlasmicSwitch.module.css"; // plasmic-import: cLCF7A0Hcm_r/css

createPlasmicElementProxy;

export type PlasmicSwitch__VariantMembers = {
  noLabel: "noLabel";
  isDisabled: "isDisabled";
  isChecked: "isChecked";
  color:
    | "error"
    | "success"
    | "warning"
    | "info"
    | "primary"
    | "secondary"
    | "accentCool"
    | "accentWarm"
    | "errorLow"
    | "errorHigh"
    | "warningLow"
    | "warningHigh"
    | "successLow"
    | "successHigh"
    | "infoHigh"
    | "infoLow"
    | "primaryLow"
    | "primaryHigh"
    | "secondaryHigh"
    | "secondaryLow"
    | "accentCoolHigh"
    | "accentCoolLow"
    | "accentWarmLow"
    | "accentWarmHigh";
};
export type PlasmicSwitch__VariantsArgs = {
  noLabel?: SingleBooleanChoiceArg<"noLabel">;
  isDisabled?: SingleBooleanChoiceArg<"isDisabled">;
  isChecked?: SingleBooleanChoiceArg<"isChecked">;
  color?: SingleChoiceArg<
    | "error"
    | "success"
    | "warning"
    | "info"
    | "primary"
    | "secondary"
    | "accentCool"
    | "accentWarm"
    | "errorLow"
    | "errorHigh"
    | "warningLow"
    | "warningHigh"
    | "successLow"
    | "successHigh"
    | "infoHigh"
    | "infoLow"
    | "primaryLow"
    | "primaryHigh"
    | "secondaryHigh"
    | "secondaryLow"
    | "accentCoolHigh"
    | "accentCoolLow"
    | "accentWarmLow"
    | "accentWarmHigh"
  >;
};
type VariantPropType = keyof PlasmicSwitch__VariantsArgs;
export const PlasmicSwitch__VariantProps = new Array<VariantPropType>(
  "noLabel",
  "isDisabled",
  "isChecked",
  "color"
);

export type PlasmicSwitch__ArgsType = {
  children?: React.ReactNode;
  name?: string;
  value?: string;
  "aria-label"?: string;
  "aria-labelledby"?: string;
  onChange?: (isChecked: boolean) => void;
};
type ArgPropType = keyof PlasmicSwitch__ArgsType;
export const PlasmicSwitch__ArgProps = new Array<ArgPropType>(
  "children",
  "name",
  "value",
  "aria-label",
  "aria-labelledby",
  "onChange"
);

export type PlasmicSwitch__OverridesType = {
  root?: p.Flex<"div">;
  toggle?: p.Flex<"div">;
  track?: p.Flex<"div">;
  thumb?: p.Flex<"div">;
  labelContainer?: p.Flex<"div">;
};

export interface DefaultSwitchProps extends pp.SwitchProps {
  "aria-label"?: string;
  "aria-labelledby"?: string;
  onChange?: (isChecked: boolean) => void;
  color?: SingleChoiceArg<
    | "error"
    | "success"
    | "warning"
    | "info"
    | "primary"
    | "secondary"
    | "accentCool"
    | "accentWarm"
    | "errorLow"
    | "errorHigh"
    | "warningLow"
    | "warningHigh"
    | "successLow"
    | "successHigh"
    | "infoHigh"
    | "infoLow"
    | "primaryLow"
    | "primaryHigh"
    | "secondaryHigh"
    | "secondaryLow"
    | "accentCoolHigh"
    | "accentCoolLow"
    | "accentWarmLow"
    | "accentWarmHigh"
  >;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSwitch__RenderFunc(props: {
  variants: PlasmicSwitch__VariantsArgs;
  args: PlasmicSwitch__ArgsType;
  overrides: PlasmicSwitch__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof p.useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "noLabel",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.noLabel
      },
      {
        path: "isDisabled",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.isDisabled
      },
      {
        path: "isChecked",
        type: "writable",
        variableType: "boolean",

        valueProp: "isChecked",
        onChangeProp: "onChange"
      },
      {
        path: "color",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.color
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const [isRootFocusVisibleWithin, triggerRootFocusVisibleWithinProps] =
    useTrigger("useFocusVisibleWithin", {
      isTextInput: false
    });
  const triggers = {
    focusVisibleWithin_root: isRootFocusVisibleWithin
  };

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_app_starter_hostless_no_auth_test_css.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root,
        {
          [sty.root___focusVisibleWithin]: triggers.focusVisibleWithin_root,
          [sty.rootcolor_accentCoolHigh]: hasVariant(
            $state,
            "color",
            "accentCoolHigh"
          ),
          [sty.rootcolor_warning]: hasVariant($state, "color", "warning"),
          [sty.rootisChecked]: hasVariant($state, "isChecked", "isChecked"),
          [sty.rootisDisabled]: hasVariant($state, "isDisabled", "isDisabled"),
          [sty.rootnoLabel]: hasVariant($state, "noLabel", "noLabel")
        }
      )}
      data-plasmic-trigger-props={[triggerRootFocusVisibleWithinProps]}
    >
      <div
        data-plasmic-name={"toggle"}
        data-plasmic-override={overrides.toggle}
        className={classNames(projectcss.all, sty.toggle, {
          [sty.toggle___focusVisibleWithin]: triggers.focusVisibleWithin_root,
          [sty.toggleisChecked]: hasVariant($state, "isChecked", "isChecked"),
          [sty.toggleisDisabled]: hasVariant($state, "isDisabled", "isDisabled")
        })}
      >
        <div
          data-plasmic-name={"track"}
          data-plasmic-override={overrides.track}
          className={classNames(projectcss.all, sty.track, {
            [sty.track___focusVisibleWithin]: triggers.focusVisibleWithin_root,
            [sty.trackcolor_accentCoolHigh]: hasVariant(
              $state,
              "color",
              "accentCoolHigh"
            ),
            [sty.trackcolor_accentCoolLow]: hasVariant(
              $state,
              "color",
              "accentCoolLow"
            ),
            [sty.trackcolor_accentCool]: hasVariant(
              $state,
              "color",
              "accentCool"
            ),
            [sty.trackcolor_accentWarmHigh]: hasVariant(
              $state,
              "color",
              "accentWarmHigh"
            ),
            [sty.trackcolor_accentWarmLow]: hasVariant(
              $state,
              "color",
              "accentWarmLow"
            ),
            [sty.trackcolor_accentWarm]: hasVariant(
              $state,
              "color",
              "accentWarm"
            ),
            [sty.trackcolor_errorHigh]: hasVariant(
              $state,
              "color",
              "errorHigh"
            ),
            [sty.trackcolor_errorLow]: hasVariant($state, "color", "errorLow"),
            [sty.trackcolor_error]: hasVariant($state, "color", "error"),
            [sty.trackcolor_infoHigh]: hasVariant($state, "color", "infoHigh"),
            [sty.trackcolor_infoLow]: hasVariant($state, "color", "infoLow"),
            [sty.trackcolor_info]: hasVariant($state, "color", "info"),
            [sty.trackcolor_primaryHigh]: hasVariant(
              $state,
              "color",
              "primaryHigh"
            ),
            [sty.trackcolor_primaryLow]: hasVariant(
              $state,
              "color",
              "primaryLow"
            ),
            [sty.trackcolor_primary]: hasVariant($state, "color", "primary"),
            [sty.trackcolor_secondaryHigh]: hasVariant(
              $state,
              "color",
              "secondaryHigh"
            ),
            [sty.trackcolor_secondaryLow]: hasVariant(
              $state,
              "color",
              "secondaryLow"
            ),
            [sty.trackcolor_secondary]: hasVariant(
              $state,
              "color",
              "secondary"
            ),
            [sty.trackcolor_successHigh]: hasVariant(
              $state,
              "color",
              "successHigh"
            ),
            [sty.trackcolor_successLow]: hasVariant(
              $state,
              "color",
              "successLow"
            ),
            [sty.trackcolor_success]: hasVariant($state, "color", "success"),
            [sty.trackcolor_warningHigh]: hasVariant(
              $state,
              "color",
              "warningHigh"
            ),
            [sty.trackcolor_warningLow]: hasVariant(
              $state,
              "color",
              "warningLow"
            ),
            [sty.trackcolor_warning]: hasVariant($state, "color", "warning"),
            [sty.trackisChecked]: hasVariant($state, "isChecked", "isChecked"),
            [sty.trackisDisabled]: hasVariant(
              $state,
              "isDisabled",
              "isDisabled"
            )
          })}
        />

        <div
          data-plasmic-name={"thumb"}
          data-plasmic-override={overrides.thumb}
          className={classNames(projectcss.all, sty.thumb, {
            [sty.thumb___focusVisibleWithin]: triggers.focusVisibleWithin_root,
            [sty.thumbcolor_accentCoolHigh]: hasVariant(
              $state,
              "color",
              "accentCoolHigh"
            ),
            [sty.thumbcolor_accentCoolLow]: hasVariant(
              $state,
              "color",
              "accentCoolLow"
            ),
            [sty.thumbcolor_accentCool]: hasVariant(
              $state,
              "color",
              "accentCool"
            ),
            [sty.thumbcolor_accentWarmHigh]: hasVariant(
              $state,
              "color",
              "accentWarmHigh"
            ),
            [sty.thumbcolor_accentWarmLow]: hasVariant(
              $state,
              "color",
              "accentWarmLow"
            ),
            [sty.thumbcolor_accentWarm]: hasVariant(
              $state,
              "color",
              "accentWarm"
            ),
            [sty.thumbcolor_errorHigh]: hasVariant(
              $state,
              "color",
              "errorHigh"
            ),
            [sty.thumbcolor_errorLow]: hasVariant($state, "color", "errorLow"),
            [sty.thumbcolor_error]: hasVariant($state, "color", "error"),
            [sty.thumbcolor_infoHigh]: hasVariant($state, "color", "infoHigh"),
            [sty.thumbcolor_infoLow]: hasVariant($state, "color", "infoLow"),
            [sty.thumbcolor_info]: hasVariant($state, "color", "info"),
            [sty.thumbcolor_primaryHigh]: hasVariant(
              $state,
              "color",
              "primaryHigh"
            ),
            [sty.thumbcolor_primaryLow]: hasVariant(
              $state,
              "color",
              "primaryLow"
            ),
            [sty.thumbcolor_primary]: hasVariant($state, "color", "primary"),
            [sty.thumbcolor_secondaryHigh]: hasVariant(
              $state,
              "color",
              "secondaryHigh"
            ),
            [sty.thumbcolor_secondaryLow]: hasVariant(
              $state,
              "color",
              "secondaryLow"
            ),
            [sty.thumbcolor_secondary]: hasVariant(
              $state,
              "color",
              "secondary"
            ),
            [sty.thumbcolor_successHigh]: hasVariant(
              $state,
              "color",
              "successHigh"
            ),
            [sty.thumbcolor_successLow]: hasVariant(
              $state,
              "color",
              "successLow"
            ),
            [sty.thumbcolor_success]: hasVariant($state, "color", "success"),
            [sty.thumbcolor_warningHigh]: hasVariant(
              $state,
              "color",
              "warningHigh"
            ),
            [sty.thumbcolor_warningLow]: hasVariant(
              $state,
              "color",
              "warningLow"
            ),
            [sty.thumbcolor_warning]: hasVariant($state, "color", "warning"),
            [sty.thumbisChecked]: hasVariant($state, "isChecked", "isChecked")
          })}
        />
      </div>
      {(hasVariant($state, "noLabel", "noLabel") ? false : true) ? (
        <div
          data-plasmic-name={"labelContainer"}
          data-plasmic-override={overrides.labelContainer}
          className={classNames(projectcss.all, sty.labelContainer, {
            [sty.labelContainer___focusVisibleWithin]:
              triggers.focusVisibleWithin_root,
            [sty.labelContainercolor_warning]: hasVariant(
              $state,
              "color",
              "warning"
            ),
            [sty.labelContainernoLabel]: hasVariant(
              $state,
              "noLabel",
              "noLabel"
            )
          })}
        >
          {p.renderPlasmicSlot({
            defaultContents: "Switch me",
            value: args.children,
            className: classNames(sty.slotTargetChildren, {
              [sty.slotTargetChildren___focusVisibleWithin]:
                triggers.focusVisibleWithin_root,
              [sty.slotTargetChildrencolor_accentCoolHigh]: hasVariant(
                $state,
                "color",
                "accentCoolHigh"
              ),
              [sty.slotTargetChildrencolor_accentCoolLow]: hasVariant(
                $state,
                "color",
                "accentCoolLow"
              ),
              [sty.slotTargetChildrencolor_accentCool]: hasVariant(
                $state,
                "color",
                "accentCool"
              ),
              [sty.slotTargetChildrencolor_accentWarmHigh]: hasVariant(
                $state,
                "color",
                "accentWarmHigh"
              ),
              [sty.slotTargetChildrencolor_accentWarmLow]: hasVariant(
                $state,
                "color",
                "accentWarmLow"
              ),
              [sty.slotTargetChildrencolor_accentWarm]: hasVariant(
                $state,
                "color",
                "accentWarm"
              ),
              [sty.slotTargetChildrencolor_errorHigh]: hasVariant(
                $state,
                "color",
                "errorHigh"
              ),
              [sty.slotTargetChildrencolor_errorLow]: hasVariant(
                $state,
                "color",
                "errorLow"
              ),
              [sty.slotTargetChildrencolor_error]: hasVariant(
                $state,
                "color",
                "error"
              ),
              [sty.slotTargetChildrencolor_infoHigh]: hasVariant(
                $state,
                "color",
                "infoHigh"
              ),
              [sty.slotTargetChildrencolor_infoLow]: hasVariant(
                $state,
                "color",
                "infoLow"
              ),
              [sty.slotTargetChildrencolor_info]: hasVariant(
                $state,
                "color",
                "info"
              ),
              [sty.slotTargetChildrencolor_primaryHigh]: hasVariant(
                $state,
                "color",
                "primaryHigh"
              ),
              [sty.slotTargetChildrencolor_primaryLow]: hasVariant(
                $state,
                "color",
                "primaryLow"
              ),
              [sty.slotTargetChildrencolor_primary]: hasVariant(
                $state,
                "color",
                "primary"
              ),
              [sty.slotTargetChildrencolor_secondaryHigh]: hasVariant(
                $state,
                "color",
                "secondaryHigh"
              ),
              [sty.slotTargetChildrencolor_secondaryLow]: hasVariant(
                $state,
                "color",
                "secondaryLow"
              ),
              [sty.slotTargetChildrencolor_secondary]: hasVariant(
                $state,
                "color",
                "secondary"
              ),
              [sty.slotTargetChildrencolor_successHigh]: hasVariant(
                $state,
                "color",
                "successHigh"
              ),
              [sty.slotTargetChildrencolor_successLow]: hasVariant(
                $state,
                "color",
                "successLow"
              ),
              [sty.slotTargetChildrencolor_success]: hasVariant(
                $state,
                "color",
                "success"
              ),
              [sty.slotTargetChildrencolor_warningHigh]: hasVariant(
                $state,
                "color",
                "warningHigh"
              ),
              [sty.slotTargetChildrencolor_warningLow]: hasVariant(
                $state,
                "color",
                "warningLow"
              ),
              [sty.slotTargetChildrencolor_warning]: hasVariant(
                $state,
                "color",
                "warning"
              ),
              [sty.slotTargetChildrenisChecked]: hasVariant(
                $state,
                "isChecked",
                "isChecked"
              ),
              [sty.slotTargetChildrennoLabel]: hasVariant(
                $state,
                "noLabel",
                "noLabel"
              )
            })
          })}
        </div>
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

function useBehavior<P extends pp.SwitchProps>(props: P, ref: pp.SwitchRef) {
  if (!("children" in props)) {
    props = {
      ...props,
      children: "Switch me"
    };
  }

  return pp.useSwitch<P, typeof PlasmicSwitch>(
    PlasmicSwitch,
    props,
    {
      isCheckedVariant: { group: "isChecked", variant: "isChecked" },
      isDisabledVariant: { group: "isDisabled", variant: "isDisabled" },
      noLabelVariant: { group: "noLabel", variant: "noLabel" },
      labelSlot: "children",
      root: "root"
    },
    ref
  );
}

const PlasmicDescendants = {
  root: ["root", "toggle", "track", "thumb", "labelContainer"],
  toggle: ["toggle", "track", "thumb"],
  track: ["track"],
  thumb: ["thumb"],
  labelContainer: ["labelContainer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  toggle: "div";
  track: "div";
  thumb: "div";
  labelContainer: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSwitch__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSwitch__VariantsArgs;
    args?: PlasmicSwitch__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSwitch__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicSwitch__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSwitch__ArgProps,
          internalVariantPropNames: PlasmicSwitch__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSwitch__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSwitch";
  } else {
    func.displayName = `PlasmicSwitch.${nodeName}`;
  }
  return func;
}

export const PlasmicSwitch = Object.assign(
  // Top-level PlasmicSwitch renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    toggle: makeNodeComponent("toggle"),
    track: makeNodeComponent("track"),
    thumb: makeNodeComponent("thumb"),
    labelContainer: makeNodeComponent("labelContainer"),

    // Metadata about props expected for PlasmicSwitch
    internalVariantProps: PlasmicSwitch__VariantProps,
    internalArgProps: PlasmicSwitch__ArgProps,

    useBehavior
  }
);

export default PlasmicSwitch;
/* prettier-ignore-end */
