kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: softwarefoundry-dev
  namespace: alyssa
  labels:
    app: softwarefoundry
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: "20"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'softwarefoundry:dev'
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: alyssa
        name: 'nodejs-20:latest'
  source:
    type: Git
    git:
      uri: 'https://github.com/seventeensierra/softwarefoundry'
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: softwarefoundry-github
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          namespace: alyssa
          name: 'nodejs-20:latest'
    - type: ConfigChange
  runPolicy: Serial