kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: softwarefoundry
  namespace: alyssa
  labels:
    app: softwarefoundry
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: "20"
spec:
  lookupPolicy:
    local: false